=begin
#Klaviyo API (Beta)

#The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

The version of the OpenAPI document: 2022-09-07.pre
Contact: developers@klaviyo.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'klaviyo_sdk_beta/api_client'
require 'klaviyo_sdk_beta/api_error'
require 'klaviyo_sdk_beta/version'
require 'klaviyo_sdk_beta/configuration'

# Models
require 'klaviyo_sdk_beta/models/catalog_category_create_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_category_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_category_create_query'
require 'klaviyo_sdk_beta/models/catalog_category_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_category_delete_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_category_delete_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_delete_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_category_delete_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_item_op'
require 'klaviyo_sdk_beta/models/catalog_category_update_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_category_update_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_update_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_category_update_query'
require 'klaviyo_sdk_beta/models/catalog_category_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_category_update_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_item_category_op'
require 'klaviyo_sdk_beta/models/catalog_item_create_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_item_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_item_create_query'
require 'klaviyo_sdk_beta/models/catalog_item_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_item_create_query_as_sub_resource_relationships'
require 'klaviyo_sdk_beta/models/catalog_item_create_query_as_sub_resource_relationships_categories'
require 'klaviyo_sdk_beta/models/catalog_item_create_query_as_sub_resource_relationships_categories_data'
require 'klaviyo_sdk_beta/models/catalog_item_delete_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_item_delete_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_delete_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_item_delete_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_update_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_item_update_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_update_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_item_update_query'
require 'klaviyo_sdk_beta/models/catalog_item_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_item_update_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_job_error_payload'
require 'klaviyo_sdk_beta/models/catalog_variant_create_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_variant_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query_as_sub_resource_relationships'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query_as_sub_resource_relationships_items'
require 'klaviyo_sdk_beta/models/catalog_variant_create_query_as_sub_resource_relationships_items_data'
require 'klaviyo_sdk_beta/models/catalog_variant_delete_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_variant_delete_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_delete_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_variant_delete_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_update_job_create_query'
require 'klaviyo_sdk_beta/models/catalog_variant_update_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_update_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/catalog_variant_update_query'
require 'klaviyo_sdk_beta/models/catalog_variant_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/catalog_variant_update_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/email_message_content'
require 'klaviyo_sdk_beta/models/email_tracking_options'
require 'klaviyo_sdk_beta/models/error_source'
require 'klaviyo_sdk_beta/models/event_create_query'
require 'klaviyo_sdk_beta/models/event_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/event_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/flow_update_query'
require 'klaviyo_sdk_beta/models/flow_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/flow_update_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/included_categories'
require 'klaviyo_sdk_beta/models/included_categories_attributes'
require 'klaviyo_sdk_beta/models/included_flow'
require 'klaviyo_sdk_beta/models/included_flow_action'
require 'klaviyo_sdk_beta/models/included_flow_actions'
require 'klaviyo_sdk_beta/models/included_flow_actions_attributes'
require 'klaviyo_sdk_beta/models/included_flow_attributes'
require 'klaviyo_sdk_beta/models/included_flow_messages'
require 'klaviyo_sdk_beta/models/included_flow_messages_attributes'
require 'klaviyo_sdk_beta/models/included_items'
require 'klaviyo_sdk_beta/models/included_items_attributes'
require 'klaviyo_sdk_beta/models/included_lists'
require 'klaviyo_sdk_beta/models/included_lists_attributes'
require 'klaviyo_sdk_beta/models/included_metrics'
require 'klaviyo_sdk_beta/models/included_metrics_attributes'
require 'klaviyo_sdk_beta/models/included_profiles'
require 'klaviyo_sdk_beta/models/included_profiles_attributes'
require 'klaviyo_sdk_beta/models/included_segments'
require 'klaviyo_sdk_beta/models/included_variants'
require 'klaviyo_sdk_beta/models/included_variants_attributes'
require 'klaviyo_sdk_beta/models/included_variants_links'
require 'klaviyo_sdk_beta/models/inline_response4_xx'
require 'klaviyo_sdk_beta/models/inline_response4_xx_errors'
require 'klaviyo_sdk_beta/models/inline_response4_xx_source'
require 'klaviyo_sdk_beta/models/list_create_query'
require 'klaviyo_sdk_beta/models/list_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/list_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/list_delete_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/list_members_add_query'
require 'klaviyo_sdk_beta/models/list_members_add_query_data'
require 'klaviyo_sdk_beta/models/list_members_delete_query'
require 'klaviyo_sdk_beta/models/list_partial_update_query'
require 'klaviyo_sdk_beta/models/list_partial_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/metric_aggregate_query'
require 'klaviyo_sdk_beta/models/metric_aggregate_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/metric_aggregate_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/metric_aggregate_row_dto'
require 'klaviyo_sdk_beta/models/metric_create_query'
require 'klaviyo_sdk_beta/models/nested_integration_filter_query'
require 'klaviyo_sdk_beta/models/onsite_profile_create_query'
require 'klaviyo_sdk_beta/models/onsite_profile_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/onsite_profile_meta'
require 'klaviyo_sdk_beta/models/onsite_profile_meta_identifiers'
require 'klaviyo_sdk_beta/models/onsite_subscription_create_query'
require 'klaviyo_sdk_beta/models/onsite_subscription_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/onsite_subscription_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/profile_create_query'
require 'klaviyo_sdk_beta/models/profile_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/profile_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/profile_location'
require 'klaviyo_sdk_beta/models/profile_partial_update_query'
require 'klaviyo_sdk_beta/models/profile_partial_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/sms_message_content'
require 'klaviyo_sdk_beta/models/sms_render_options'
require 'klaviyo_sdk_beta/models/sms_tracking_options'
require 'klaviyo_sdk_beta/models/segment_partial_update_query'
require 'klaviyo_sdk_beta/models/segment_partial_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/send_options'
require 'klaviyo_sdk_beta/models/subscription'
require 'klaviyo_sdk_beta/models/subscription_create_job_create_query'
require 'klaviyo_sdk_beta/models/subscription_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/subscription_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/suppression'
require 'klaviyo_sdk_beta/models/suppression_create_job_create_query'
require 'klaviyo_sdk_beta/models/suppression_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/suppression_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/template_clone_query'
require 'klaviyo_sdk_beta/models/template_clone_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/template_clone_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/template_create_query'
require 'klaviyo_sdk_beta/models/template_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/template_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/template_delete_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/template_render_query'
require 'klaviyo_sdk_beta/models/template_render_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/template_render_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/template_update_query'
require 'klaviyo_sdk_beta/models/template_update_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/template_update_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/unsubscription_create_job_create_query'
require 'klaviyo_sdk_beta/models/unsubscription_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/unsubscription_create_job_create_query_as_sub_resource_attributes'
require 'klaviyo_sdk_beta/models/unsuppression_create_job_create_query'
require 'klaviyo_sdk_beta/models/unsuppression_create_job_create_query_as_sub_resource'
require 'klaviyo_sdk_beta/models/utm_param_info'

# APIs
require 'klaviyo_sdk_beta/api/catalogs_api'
require 'klaviyo_sdk_beta/api/client_api'
require 'klaviyo_sdk_beta/api/events_api'
require 'klaviyo_sdk_beta/api/flows_api'
require 'klaviyo_sdk_beta/api/lists_api'
require 'klaviyo_sdk_beta/api/metrics_api'
require 'klaviyo_sdk_beta/api/profiles_api'
require 'klaviyo_sdk_beta/api/segments_api'
require 'klaviyo_sdk_beta/api/templates_api'

# retry logic
require 'retriable'

module KlaviyoBeta
  @is_initialized = false

  class << self
    # Customize default settings for the SDK using block.
    #   KlaviyoBeta.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.

 
    # add retriable config
    # todo: check how slow this is
    Configuration.default.class.module_eval { attr_accessor :max_retries, :max_delay }

    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end

      # create wrapper classes
      if !@is_initialized # run this only once
        self.constants.each do |c|
          if c[-3..-1] == "Api"
            attributes = [:attr1]
            wrapper_class = KlaviyoBeta.const_set(c[0..-4], Struct.new(*attributes))
            original_class = KlaviyoBeta.const_get(c)
            
            # recreate methods
            original_class.public_instance_methods(false).each do |m|
              wrapper_class.class_eval { 
                define_singleton_method m do |*arg| 
                  # max_delay=60, max_retries=3
                  # retry_codes = [429,503,504]
                  # only add retriable if both of these are not set
                  max_retries = Configuration.default.max_retries
                  max_delay = Configuration.default.max_delay

                  if (max_retries != nil && max_delay != nil)
                    Retriable.configure do |c|
                      c.tries = max_retries
                      c.max_elapsed_time = max_delay
                      c.on = {
                        KlaviyoBeta::ApiError => [/429/, /503/, /504/]
                      }
                    end
                    Retriable.retriable do
                      KlaviyoBeta.const_get(c).new.send(m, *arg)
                    end
                  else
                    KlaviyoBeta.const_get(c).new.send(m, *arg)
                  end
                end
              }
            end
          end
        end
        @is_initialized = true
      end
    end
  end
end
